language: python
python:
  - 2.7
  - 3.4

sudo: required

addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libbz2-dev
            - liblzo2-dev
            - liblapack-dev
            - python-software-properties
            - python-numpy
            - python-scipy

virtualenv:
    system_site_packages: true

before_script:
    - sudo apt-add-repository ppa:speth/cantera -y
    - sudo aptitude update
    - sudo aptitude install cantera-python cantera-python3 cantera-dev -y

# command to install dependencies
install: pip install -r requirements.txt

# command to run tests
script: py.test
