language: python
python:
  - 2.7
 #- 3.4

sudo: required

addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libbz2-dev
            - liblzo2-dev
            - liblapack-dev
            - python-software-properties

virtualenv:
    system_site_packages: true

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y g++ python-dev scons python-numpy python-numpy-dev python-scipy cython libsundials-serial-dev liblapack-dev libblas-dev libboost-thread-dev python3-dev python3-numpy-dev
    - git clone https://github.com/Cantera/cantera.git
    - cd cantera
    - git checkout 2.2
    - scons build -j4 blas_lapack_libs=lapack,blas
    #- sudo apt-add-repository ppa:speth/cantera -y
    #- sudo aptitude update
    #- sudo aptitude install cantera-python cantera-python3 cantera-dev -y

# command to install dependencies
install: pip install -r requirements.txt

# command to run tests
script: py.test
