language: python
python:
  - 2.7
 #- 3.4

sudo: required

addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libbz2-dev
            - liblzo2-dev
            - liblapack-dev
            - python-software-properties

virtualenv:
    system_site_packages: true

# Install packages
install:
    - sudo apt-get update
      # We do this conditionally because it saves us some downloading if the
      # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
      # Useful for debugging any issues with conda
    - conda info -a

    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pytables
    - source activate test-environment
    - python setup.py install

    - sudo apt-get update -qq
    - sudo apt-get install -y g++ python-dev scons cython libsundials-serial-dev liblapack-dev libblas-dev libboost-thread-dev
    - git clone https://github.com/Cantera/cantera.git
    - cd cantera && git checkout 2.2 && scons build -j4 blas_lapack_libs=lapack,blas
    #- sudo apt-add-repository ppa:speth/cantera -y
    #- sudo aptitude update
    #- sudo aptitude install cantera-python cantera-python3 cantera-dev -y
    #- pip install -r requirements.txt

# command to run tests
script: py.test
