sudo: required
language: python

matrix:
  include:
    - os: linux
      env: PYTHON="3.5"

    - os: linux
      env: PYTHON="3.6"

    - os: osx
      env: PYTHON="3.5"

    - os: osx
      env: PYTHON="3.6"

# Install packages
install:
    - sudo apt-get update
      # We do this conditionally because it saves us some downloading if the
      # version is the same.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda config --append channels conda-forge
    - sed -i -e "s/\${PYTHON}/"${PYTHON}"/" test-environment.yaml
    - if [[ -z "$TRAVIS_TAG" ]]; then
        conda env create -qf test-environment.yaml;
        source activate test-environment;
      else
        conda install -q conda-build anaconda-client;
      fi
      # Useful for debugging any issues with conda
    - conda info -a
    - conda list

    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

# command to run tests
script: py.test -vv
